version: '3'
services:
  php-apache:
    image: php:apache
    container_name: laravel
    ports:
      - 80:80
    volumes:
      - ./test01:/var/www/html/
    networks:
      - laravel-shouts
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user001
      - MYSQL_PASSWORD=123456
    volumes:
      - ./data:/var/lib/mysql   
    networks:
      - laravel-shouts 
networks:
    laravel-shouts: